"""
Build a SOC-analyst report from a scored query.

    from fusion import score_query
    from reports import build_report, render_markdown

    score  = score_query(query, records)
    report = build_report(query, score, records)
    print(render_markdown(report))

The headline is first, and that is a design decision rather than a layout one
(design §2.9). An analyst working a queue reads the band and stops there when it
is GREEN; everything below — score, case, evidence, reasoning — is the supporting
detail they open when it is not, or when they want to verify a GREEN. Putting the
composite score first would invite reading a number without its context, which is
the failure mode the case taxonomy exists to prevent.

Every number in the reasoning narrative arrives through `narrative.Fact` carrying
a JSON pointer into this report. Nothing here is generated by a language model,
and `test_reports.py` proves it by resolving every figure in the rendered text
back to a value at a real path.
"""

from __future__ import annotations

import hashlib
import sys
from datetime import datetime, timezone
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any, Sequence

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from fusion.cases import (  # noqa: E402
    ACCEPT, REVIEW, REJECT, ESCALATE, GREEN, ORANGE, RED,
    ATTACK_DETECTED, TRUSTED_SOURCE_COMPROMISE, HEADLINE_LABEL, SUBTYPE_LABEL,
)
from fusion.confidence import REVIEW_FLOOR, SINGLETON_CAP  # noqa: E402

from .entities import extract_from_documents, group_by_kind  # noqa: E402
from .narrative import (  # noqa: E402
    Fact, FMT_DELTA, FMT_PERCENT, FMT_PLAIN, FMT_SCORE, FMT_TEXT,
    Narrative, NarrativeBuilder,
)
from .schema import (  # noqa: E402
    REPORT_SCHEMA_VERSION, AnalystDecisionBlock, DocumentSection, SignalReading,
    risk_tier_for,
)

# Analyst-facing names for the detector signals. The internal names are terse and
# one of them is inverted relative to intuition, so both are carried.
SIGNAL_DISPLAY = {
    "injection": "injection_probability",
    "anomaly": "embedding_anomaly_score",
    "unsupport": "claim_unsupport_score",
    "conflict": "evidence_conflict_score",
}

SIGNAL_NOTE = {
    "unsupport": ("Risk-oriented complement of the entailment score: higher means the "
                  "evidence supports the claim LESS."),
    "anomaly": "Within-set robust z-score, normalised against this query's own retrieval set.",
    "conflict": "Retrieved evidence versus the model's parametric knowledge. Not yet built.",
}

STATUS_OVER_MAL = "over_malicious"
STATUS_OVER_SUS = "over_suspicious"
STATUS_BELOW = "below"
STATUS_UNUSABLE = "unusable"
STATUS_MISSING = "missing"


@dataclass
class Report:
    """The full analyst report. Serialises to JSON; renders to text via `render.py`."""

    schema_version: str
    report_id: str
    generated_at: str

    # --- headline, first and deliberately so ---
    headline: str
    headline_label: str
    headline_subtype: str | None
    headline_subtype_label: str | None
    headline_display: str
    headline_meaning: str

    # --- supporting detail ---
    query: str
    case_id: str
    case_name: str
    case_rationale: str
    priority: str
    risk_tier: str
    recommended_action: str
    action_meaning: str

    trust_percent: float | None
    trust_interval: list[float | None]
    risk: float | None
    risk_interval: list[float | None]
    confidence: float
    confidence_components: dict[str, float]
    confidence_caps: list[str]

    tier_governing: int
    n_retrieved: int
    n_eff: float
    band: str

    documents: list[DocumentSection] = field(default_factory=list)
    entities: dict[str, list[dict[str, Any]]] = field(default_factory=dict)
    entity_count: int = 0

    reasoning: dict[str, Any] = field(default_factory=dict)
    analyst_decision: dict[str, Any] = field(default_factory=dict)

    provenance: dict[str, Any] = field(default_factory=dict)
    caveats: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["documents"] = [x.to_dict() if hasattr(x, "to_dict") else x
                          for x in self.documents]
        return d


# ---------------------------------------------------------------------------
# Signal readings
# ---------------------------------------------------------------------------

def _reading(signal: str, value: float | None, thresholds: Any,
             backends: dict[str, Any] | None) -> SignalReading:
    """Judge one signal against its thresholds, distinguishing four outcomes.

    The distinction between *below threshold*, *unusable* and *missing* is carried
    all the way into the report rather than collapsed into "not flagged". They mean
    different things to an analyst: below threshold is a measurement, unusable means
    the detector could not be calibrated at all, and missing means it never ran.
    Reporting all three as a quiet signal would overstate what the system checked.
    """
    unusable = getattr(thresholds, "unusable", {}) or {}
    sus = (getattr(thresholds, "suspicious", {}) or {}).get(signal)
    mal = (getattr(thresholds, "malicious", {}) or {}).get(signal)

    backend_name, is_model = None, None
    if backends:
        key = {"unsupport": "entailment"}.get(signal, signal)
        info = backends.get(key) or {}
        if isinstance(info, dict):
            backend_name = info.get("name") or info.get("backend")
            is_model = info.get("is_model")

    if signal in unusable:
        return SignalReading(signal, value, sus, mal, None, None, STATUS_UNUSABLE,
                             backend_name, is_model, note=unusable[signal])
    if value is None:
        return SignalReading(signal, None, sus, mal, None, None, STATUS_MISSING,
                             backend_name, is_model, note=SIGNAL_NOTE.get(signal))

    margin_sus = (value - sus) if sus is not None else None
    margin_mal = (value - mal) if mal is not None else None
    if mal is not None and value >= mal:
        status = STATUS_OVER_MAL
    elif sus is not None and value >= sus:
        status = STATUS_OVER_SUS
    else:
        status = STATUS_BELOW
    return SignalReading(signal, value, sus, mal, margin_sus, margin_mal, status,
                         backend_name, is_model, note=SIGNAL_NOTE.get(signal))


# ---------------------------------------------------------------------------
# Narrative assembly
# ---------------------------------------------------------------------------

def _f(key: str, value: Any, path: str, fmt: str = FMT_SCORE) -> Fact:
    return Fact(key=key, value=value, path=path, fmt=fmt)


def _build_narrative(report_d: dict[str, Any], sections: list[DocumentSection],
                     detail: dict[str, Any]) -> Narrative:
    """Assemble the reasoning text. Every slot is filled from a Fact with a path.

    The pointers below (`/headline`, `/documents/0/...`) are resolved by the
    grounding test against the finished report, so a wrong path fails the build
    rather than producing a sentence that merely looks right.
    """
    nb = NarrativeBuilder()
    head = report_d["headline"]
    tier = report_d["tier_governing"]

    # --- 1. the headline, restated with its reason ---
    if head == RED:
        tid = ("headline_red_compromise"
               if report_d["headline_subtype"] == TRUSTED_SOURCE_COMPROMISE
               else "headline_red_attack")
        nb.add(tid,
               _f("headline", head, "/headline", FMT_TEXT),
               _f("case_id", report_d["case_id"], "/case_id", FMT_TEXT),
               _f("case_name", report_d["case_name"], "/case_name", FMT_TEXT),
               _f("tier", tier, "/tier_governing", FMT_PLAIN))
    elif head == GREEN:
        nb.add("headline_green",
               _f("headline", head, "/headline", FMT_TEXT),
               _f("headline_label", report_d["headline_label"], "/headline_label", FMT_TEXT),
               _f("tier", tier, "/tier_governing", FMT_PLAIN))
    elif detail.get("headline_rule", "").startswith("tier_not_"):
        nb.add("headline_orange_tier",
               _f("headline", head, "/headline", FMT_TEXT),
               _f("headline_label", report_d["headline_label"], "/headline_label", FMT_TEXT),
               _f("tier", tier, "/tier_governing", FMT_PLAIN))
    else:
        nb.add("headline_orange_review",
               _f("headline", head, "/headline", FMT_TEXT),
               _f("headline_label", report_d["headline_label"], "/headline_label", FMT_TEXT),
               _f("action", report_d["recommended_action"], "/recommended_action", FMT_TEXT))

    # --- 2. which detectors fired, and by how much ---
    fired = False
    for i, sec in enumerate(sections):
        for j, r in enumerate(sec.readings):
            if r.status not in (STATUS_OVER_MAL, STATUS_OVER_SUS):
                continue
            fired = True
            over_mal = r.status == STATUS_OVER_MAL
            thr = r.malicious_threshold if over_mal else r.suspicious_threshold
            margin = r.margin_to_malicious if over_mal else r.margin_to_suspicious
            base = f"/documents/{i}/readings/{j}"
            thr_path = f"{base}/" + ("malicious_threshold" if over_mal else "suspicious_threshold")
            margin_path = f"{base}/" + ("margin_to_malicious" if over_mal
                                        else "margin_to_suspicious")
            nb.add("signal_over_malicious" if r.status == STATUS_OVER_MAL
                   else "signal_over_suspicious",
                   _f("signal", SIGNAL_DISPLAY.get(r.signal, r.signal),
                      f"/documents/{i}/readings/{j}/signal", FMT_TEXT),
                   _f("value", r.value, f"/documents/{i}/readings/{j}/value"),
                   _f("doc_id", sec.doc_id, f"/documents/{i}/doc_id", FMT_TEXT),
                   _f("threshold", thr, thr_path),
                   _f("margin", margin, margin_path, FMT_DELTA),
                   _f("tier", sec.source_tier, f"/documents/{i}/source_tier", FMT_PLAIN))

    if not fired:
        nb.add("no_signal_fired",
               _f("n_docs", report_d["n_retrieved"], "/n_retrieved", FMT_PLAIN))

    # Signals that could not be judged at all -- reported once, at response level.
    seen: set[str] = set()
    for i, sec in enumerate(sections):
        for j, r in enumerate(sec.readings):
            if r.signal in seen:
                continue
            if r.status == STATUS_UNUSABLE:
                seen.add(r.signal)
                nb.add("signal_unusable",
                       _f("signal", SIGNAL_DISPLAY.get(r.signal, r.signal),
                          f"/documents/{i}/readings/{j}/signal", FMT_TEXT))
            elif r.status == STATUS_MISSING:
                seen.add(r.signal)
                nb.add("signal_missing",
                       _f("signal", SIGNAL_DISPLAY.get(r.signal, r.signal),
                          f"/documents/{i}/readings/{j}/signal", FMT_TEXT))

    # --- 3. the composite score ---
    if report_d["trust_percent"] is not None:
        nb.add("composite_score",
               _f("trust", report_d["trust_percent"], "/trust_percent", FMT_PERCENT),
               _f("trust_low", report_d["trust_interval"][0], "/trust_interval/0", FMT_PERCENT),
               _f("trust_high", report_d["trust_interval"][1], "/trust_interval/1", FMT_PERCENT))
    else:
        nb.add("composite_absent")

    # --- 4. confidence ---
    conf = report_d["confidence"]
    if any("singleton" in c for c in report_d["confidence_caps"]):
        nb.add("confidence_singleton",
               _f("cap", SINGLETON_CAP, "/provenance/confidence_singleton_cap"))
    if conf < REVIEW_FLOOR:
        nb.add("confidence_low",
               _f("confidence", conf, "/confidence"),
               _f("floor", REVIEW_FLOOR, "/provenance/confidence_review_floor"))
    else:
        nb.add("confidence_high",
               _f("confidence", conf, "/confidence"),
               _f("n_eff", report_d["n_eff"], "/n_eff", FMT_PLAIN),
               _f("n_sources", report_d["provenance"]["n_distinct_sources"],
                  "/provenance/n_distinct_sources", FMT_PLAIN))

    # --- 5. how the two tracks were reconciled ---
    tax, sco = detail.get("taxonomy_action"), detail.get("score_action")
    if tax and sco:
        if tax == sco:
            nb.add("reconciliation_agree",
                   _f("action", report_d["recommended_action"], "/recommended_action", FMT_TEXT))
        else:
            nb.add("reconciliation_differ",
                   _f("taxonomy_action", tax, "/provenance/taxonomy_action", FMT_TEXT),
                   _f("score_action", sco, "/provenance/score_action", FMT_TEXT),
                   _f("action", report_d["recommended_action"], "/recommended_action", FMT_TEXT))

    # --- 6. indicators ---
    if report_d["entity_count"]:
        summary = ", ".join(f"{len(v)} {k}" for k, v in sorted(report_d["entities"].items()))
        nb.add("entities_found",
               _f("n_entities", report_d["entity_count"], "/entity_count", FMT_PLAIN),
               _f("entity_summary", summary, "/entities", FMT_TEXT))
    else:
        nb.add("entities_none")

    # --- 7. caveats, so no fallback figure can be read as a measurement ---
    fallbacks = [name for name, info in (detail.get("detector_backends") or {}).items()
                 if isinstance(info, dict) and info.get("is_model") is False]
    if fallbacks:
        nb.add("backend_fallback",
               _f("n_fallback", len(fallbacks), "/provenance/n_fallback_backends", FMT_PLAIN),
               _f("fallback_list", ", ".join(sorted(fallbacks)),
                  "/provenance/fallback_backends", FMT_TEXT))
    if detail.get("bands_fitted") is False:
        nb.add("model_unfitted")

    return nb.build()


# ---------------------------------------------------------------------------
# The public call
# ---------------------------------------------------------------------------

def build_report(
    query: str,
    score: Any,
    retrieved_docs: Sequence[Any],
    *,
    thresholds: Any = None,
    generated_at: str | None = None,
) -> Report:
    """Turn a `fusion.QueryScore` plus its retrieval set into an analyst report.

    `thresholds` defaults to the band thresholds the scorer used, so the numbers
    cited in the narrative are the ones the decision was actually made against
    rather than a freshly loaded set that may have been recalibrated since.
    """
    if score is None:
        raise ValueError("no QueryScore to report on")

    now = generated_at or datetime.now(timezone.utc).isoformat(timespec="seconds")
    detail = dict(getattr(score, "detail", {}) or {})
    backends = detail.get("detector_backends") or {}
    by_id = {d.doc_id: d for d in retrieved_docs}

    if thresholds is None:
        thresholds = _default_thresholds()

    # --- per-document sections ---
    sections: list[DocumentSection] = []
    for rank, ds in enumerate(getattr(score, "documents", []) or [], start=1):
        rec = by_id.get(ds.doc_id)
        prov = rec.provenance if rec is not None else None
        readings = [_reading(s, ds.signals.get(s), thresholds, backends)
                    for s in ("injection", "anomaly", "unsupport", "conflict")]
        ents = extract_from_documents([rec]) if rec is not None else []
        sections.append(DocumentSection(
            rank=rank, doc_id=ds.doc_id,
            title=getattr(rec, "title", "") if rec is not None else "",
            source_id=ds.source_id,
            source_name=getattr(prov, "source_name", "") if prov else "",
            source_tier=ds.source_tier,
            source_tier_label=getattr(prov, "source_tier_label", "") if prov else "",
            similarity=ds.similarity,
            case_id=ds.case_id, case_name=ds.case_name,
            headline=ds.headline, headline_subtype=ds.headline_subtype,
            action=ds.action, priority=ds.priority,
            trust_percent=_nan_to_none(ds.trust_percent),
            risk=_nan_to_none(ds.risk),
            signals=dict(ds.signals), readings=readings,
            provenance=prov.to_dict() if prov is not None else {},
            entities=[e.to_dict() for e in ents],
        ))

    # --- indicators across the whole retrieval set ---
    all_entities = extract_from_documents(retrieved_docs)
    grouped = {k: [e.to_dict() for e in v]
               for k, v in group_by_kind(all_entities).items()}

    subtype = score.headline_subtype
    display = score.headline + (f" — {SUBTYPE_LABEL[subtype]}" if subtype else "")

    fallbacks = sorted(name for name, info in backends.items()
                       if isinstance(info, dict) and info.get("is_model") is False)

    report = Report(
        schema_version=REPORT_SCHEMA_VERSION,
        report_id=_report_id(query, now),
        generated_at=now,
        headline=score.headline,
        headline_label=score.headline_label,
        headline_subtype=subtype,
        headline_subtype_label=score.headline_subtype_label,
        headline_display=display,
        headline_meaning=score.headline_meaning,
        query=query,
        case_id=score.case_id, case_name=score.case_name,
        case_rationale=detail.get("case_rationale", ""),
        priority=score.priority,
        risk_tier=risk_tier_for(score.priority, score.action),
        recommended_action=score.action, action_meaning=score.action_meaning,
        trust_percent=_nan_to_none(score.trust_percent),
        trust_interval=[_nan_to_none(v) for v in score.confidence_interval],
        risk=_nan_to_none(score.risk),
        risk_interval=[_nan_to_none(v) for v in score.risk_interval],
        confidence=score.confidence,
        confidence_components=detail.get("confidence_components", {}),
        confidence_caps=list(detail.get("confidence_caps", []) or []),
        tier_governing=score.tier_governing,
        n_retrieved=score.n_retrieved, n_eff=score.n_eff, band=score.band,
        documents=sections,
        entities=grouped, entity_count=len(all_entities),
        provenance={
            "n_distinct_sources": len({d.source_id for d in sections}),
            "n_distinct_tiers": len({d.source_tier for d in sections}),
            "detector_backends": backends,
            "fallback_backends": ", ".join(fallbacks),
            "n_fallback_backends": len(fallbacks),
            "taxonomy_action": detail.get("taxonomy_action"),
            "score_action": detail.get("score_action"),
            "headline_rule": detail.get("headline_rule"),
            "reconciliation": detail.get("reconciliation"),
            "all_matched_cases": detail.get("all_matched_cases", []),
            "model_fitted": detail.get("model_fitted"),
            "bands_fitted": detail.get("bands_fitted"),
            "hypothesis_source": detail.get("hypothesis_source"),
            "operating_regime": detail.get("operating_regime"),
            "confidence_review_floor": REVIEW_FLOOR,
            "confidence_singleton_cap": SINGLETON_CAP,
        },
        caveats=_caveats(detail, fallbacks),
    )

    # The narrative is built LAST, against the finished report dict, so every
    # JSON pointer it records resolves against the object that will be served.
    d = report.to_dict()
    report.reasoning = _build_narrative(d, sections, detail).to_dict()

    report.analyst_decision = AnalystDecisionBlock.pending(
        system_recommended_action=score.action,
        system_case_id=score.case_id,
        system_risk_score=_nan_to_none(score.risk),
        system_confidence=score.confidence,
        system_headline=score.headline,
        doc_ids=[s.doc_id for s in sections],
    ).to_dict()

    return report


def _default_thresholds() -> Any:
    """The band thresholds the scorer would have used.

    Loaded from the fitted artefact when one exists, and provisional otherwise.
    Provisional thresholds are clearly marked as such and flow through to the
    report's caveats, so a report built before training says so rather than citing
    placeholder cut points as if they were calibrated.
    """
    from fusion.bands import BandThresholds  # noqa: PLC0415
    from fusion.scorer import THRESHOLDS_PATH  # noqa: PLC0415
    if THRESHOLDS_PATH.exists():
        try:
            return BandThresholds.load(THRESHOLDS_PATH)
        except Exception:
            pass
    return BandThresholds.provisional()


def _caveats(detail: dict[str, Any], fallbacks: list[str]) -> list[str]:
    out: list[str] = []
    if fallbacks:
        out.append(
            f"{len(fallbacks)} detector(s) ran on fallback backends ({', '.join(fallbacks)}). "
            f"Scores are structural indicators, not measurements of detection performance.")
    if detail.get("model_fitted") is False:
        out.append("No fitted model: the case taxonomy ran alone and no composite score "
                   "is reported.")
    if detail.get("bands_fitted") is False:
        out.append("Band thresholds are provisional rather than fitted to a corpus.")
    if detail.get("hypothesis_source") == "query_proxy":
        out.append("Entailment used the query as the hypothesis because no generated answer "
                   "was supplied; it measures support for the QUESTION, not the ANSWER.")
    return out


def _nan_to_none(value: Any) -> Any:
    """NaN is how the scorer says 'not computed'. JSON has no NaN, and `null` is
    the honest encoding — `0.0` would read as a measured zero."""
    try:
        return None if value is None or value != value else value
    except TypeError:
        return value


def _report_id(query: str, timestamp: str) -> str:
    digest = hashlib.sha256(f"{query}|{timestamp}".encode("utf-8")).hexdigest()
    return f"rpt-{digest[:16]}"
